---
title: "cellchat"
author: "YueanZhao"
date: '2023-05-19'
output: html_document
---

# fig4 influenza B virus cell & P6_T_1,P6_T_6,P6_T_9,P6_T_10

```{r}
scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
DefaultAssay(scRNAsubT8) <- "RNA"

scRNA_P6 <- readRDS("rds/scRNA_P6_fluB.rds")
DefaultAssay(scRNA_P6) <- "RNA"
```

```{r}
fluB <- scRNA_P6[,!is.na(scRNA_P6$fluB)]
fluB[["cellchat"]] <- "Influenza B Virus"
fluB <- SetIdent(fluB,value = "cellchat")

TCR <- scRNAsubT8[,scRNAsubT8$TCR_ID %in% c("P6_T_1","P6_T_6","P6_T_9","P6_T_10")]
TCR[["cellchat"]] <- TCR$TCR_ID
TCR <- SetIdent(TCR,value = "cellchat")

seurat_obj <- merge(x = fluB, y = TCR)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```


```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Cell-Cell Contact")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("Influenza B Virus", "P6_T_1","P6_T_10","P6_T_6","P6_T_9"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_flu_P6T1&6&9&10_MHCI.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig4 P6 freq>10 TCR MHCI score

```{r}
scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
DefaultAssay(scRNAsubT8) <- "RNA"

scRNA_P6 <- readRDS("rds/scRNA_P6_fluB.rds")
DefaultAssay(scRNA_P6) <- "RNA"
```

```{r}
TCR <- scRNAsubT8[,scRNAsubT8$patient == "P6" & scRNAsubT8$freq_bchain_patient >= 10]
TCR[["cellchat"]] <- TCR$TCR_ID
TCR <- SetIdent(TCR,value = "cellchat")

fluB <- scRNA_P6[,!is.na(scRNA_P6$fluB)]
fluB[["cellchat"]] <- "Influenza B Virus"
fluB <- SetIdent(fluB,value = "cellchat")

seurat_obj <- merge(x = fluB, y = TCR)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Cell-Cell Contact")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)
cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)

cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
pathways.show <- c("MHC-I")
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_flu_P6TCR(>10)_MHCI.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig6 BALF_tMDM_CCL2 & T8
```{r}
scRNAsubM <- readRDS("rds/scRNAsubM_macro&mono_anno.rds")
DefaultAssay(scRNAsubM) <- "RNA"

scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
DefaultAssay(scRNAsubT8) <- "RNA"
```

```{r}
tMDM <- scRNAsubM[,scRNAsubM$cell_type == "transitioning MDM_CCL2" & scRNAsubM$sample_type == "BALF"]
tMDM[["cellchat"]] <- "BALF_tMDM_CCL2"
tMDM <- SetIdent(tMDM,value = "cellchat")

scRNAsubT8[["cellchat"]] <- scRNAsubT8$cell_type_main
scRNAsubT8 <- SetIdent(scRNAsubT8,value = "cellchat")

seurat_obj <- merge(x = scRNAsubT8, y = tMDM)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("T8_naive","T8_cm","T8_em","T8_rm","T8_emra/eff",
                                "T8_NK-like","Cycling", "MAIT","BALF_tMDM_CCL2"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-tMDM-CCL2_T8.rds")
```

```{r}
rm(list = ls())
gc()
```
# fig6 BALF_tMDM_CCL2 & T4
```{r}
scRNAsubM <- readRDS("rds/scRNAsubM_macro&mono_anno.rds")
DefaultAssay(scRNAsubM) <- "RNA"

scRNAsubT4 <- readRDS("rds/scRNAsubT4_anno_TCRID_Cycling.NoCD8A.rds")
DefaultAssay(scRNAsubT4) <- "RNA"
```

```{r}
tMDM <- scRNAsubM[,scRNAsubM$cell_type == "transitioning MDM_CCL2" & scRNAsubM$sample_type == "BALF"]
tMDM[["cellchat"]] <- "BALF_tMDM_CCL2"
tMDM <- SetIdent(tMDM,value = "cellchat")

scRNAsubT4[["cellchat"]] <- scRNAsubT4$cell_type_main
scRNAsubT4 <- SetIdent(scRNAsubT4,value = "cellchat")

seurat_obj <- merge(x = scRNAsubT4, y = tMDM)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("T4_Tn","T4_Treg","T4_Tm","T4_Tfh","T4_Th1","T4_Th17","T4_Th2",
                                "T4_CTL","Cycling","BALF_tMDM_CCL2"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))


```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-tMDM-CCL2_T4.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig6 BALF_tMDM_CCL2 & B/Plasma

```{r}
scRNAsubM <- readRDS("rds/scRNAsubM_macro&mono_anno.rds")
DefaultAssay(scRNAsubM) <- "RNA"

scRNAsubB <- readRDS("rds/scRNAsubB_anno_BCR.rds")
DefaultAssay(scRNAsubB) <- "RNA"
```

```{r}
tMDM <- scRNAsubM[,scRNAsubM$cell_type == "transitioning MDM_CCL2" & scRNAsubM$sample_type == "BALF"]
tMDM[["cellchat"]] <- "BALF_tMDM_CCL2"
tMDM <- SetIdent(tMDM,value = "cellchat")

scRNAsubB[["cellchat"]] <- scRNAsubB$cell_type
scRNAsubB <- SetIdent(scRNAsubB,value = "cellchat")

seurat_obj <- merge(x = scRNAsubB, y = tMDM)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("B_MZ","B_naive","B_GC","B_pre_mem","B_mem",
                                "PB","PC.1","PC.2","PC.3","BALF_tMDM_CCL2"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-tMDM-CCL2_B&P.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig6 Mono & Macro

```{r}
scRNAsubM <- readRDS("rds/scRNAsubM_macro&mono_anno.rds")
DefaultAssay(scRNAsubM) <- "RNA"

scRNAsubM$cellchat <- scRNAsubM$cell_type
scRNAsubM$cellchat <- gsub("transitioning MDM_CCL2","tMDM_CCL2",scRNAsubM$cellchat)
scRNAsubM$cellchat <- gsub("transitioning MDM_FMN1","tMDM_FMN1",scRNAsubM$cellchat)
```


```{r}
data.input <- GetAssayData(scRNAsubM, assay = "RNA", slot = "data")
identity <- subset(scRNAsubM@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("Mono_CD14","Mono_CD14_CD16","Mono_CD16","tMDM_CCL2",
                                "tMDM_FMN1","MDM_CCL18","AM_FABP4"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_Mono&Macro.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig6 BALF_ciliated & mono/macro

```{r}
scRNAsubM <- readRDS("rds/scRNAsubM_macro&mono_anno.rds")
DefaultAssay(scRNAsubM) <- "RNA"

scRNAsubE <- readRDS("rds/scRNAsubE_anno.rds")
DefaultAssay(scRNAsubE) <- "RNA"
```

```{r}
ciliated <- scRNAsubE[,scRNAsubE$cell_type == "Ciliated cells" & scRNAsubE$sample_type == "BALF"]
ciliated[["cellchat"]] <- "BALF Ciliated Epi"
ciliated <- SetIdent(ciliated,value = "cellchat")

scRNAsubM[["cellchat"]] <- scRNAsubM$cell_type
scRNAsubM$cellchat <- gsub("transitioning MDM_CCL2","tMDM_CCL2",scRNAsubM$cellchat)
scRNAsubM$cellchat <- gsub("transitioning MDM_FMN1","tMDM_FMN1",scRNAsubM$cellchat)
scRNAsubM <- SetIdent(scRNAsubM,value = "cellchat")

seurat_obj <- merge(x = scRNAsubM, y = ciliated)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("Mono_CD14","Mono_CD14_CD16","Mono_CD16","tMDM_CCL2",
                                "tMDM_FMN1","MDM_CCL18","AM_FABP4","BALF Ciliated Epi"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-ciliated_mono&macro.rds")
```

```{r}
rm(list = ls())
gc()
```

# fig6 BALF_ciliated & B/Plasma

```{r}
scRNAsubB <- readRDS("rds/scRNAsubB_anno_BCR.rds")
DefaultAssay(scRNAsubB) <- "RNA"

scRNAsubE <- readRDS("rds/scRNAsubE_anno.rds")
DefaultAssay(scRNAsubE) <- "RNA"
```

```{r}
ciliated <- scRNAsubE[,scRNAsubE$cell_type == "Ciliated cells" & scRNAsubE$sample_type == "BALF"]
ciliated[["cellchat"]] <- "BALF Ciliated Epi"
ciliated <- SetIdent(ciliated,value = "cellchat")

scRNAsubB[["cellchat"]] <- scRNAsubB$cell_type
scRNAsubB <- SetIdent(scRNAsubB,value = "cellchat")

seurat_obj <- merge(x = scRNAsubB, y = ciliated)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("B_MZ","B_naive","B_GC","B_pre_mem","B_mem",
                                "PB","PC.1","PC.2","PC.3","BALF Ciliated Epi"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))
```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-ciliated_B&P.rds")
```

```{r}
rm(list = ls())
gc()
```


# fig6 BALF_ciliated & T8

```{r}
scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
DefaultAssay(scRNAsubT8) <- "RNA"

scRNAsubE <- readRDS("rds/scRNAsubE_anno.rds")
DefaultAssay(scRNAsubE) <- "RNA"
```

```{r}
ciliated <- scRNAsubE[,scRNAsubE$cell_type == "Ciliated cells" & scRNAsubE$sample_type == "BALF"]
ciliated[["cellchat"]] <- "BALF Ciliated Epi"
ciliated <- SetIdent(ciliated,value = "cellchat")

scRNAsubT8[["cellchat"]] <- scRNAsubT8$cell_type_main
scRNAsubT8 <- SetIdent(scRNAsubT8,value = "cellchat")

seurat_obj <- merge(x = scRNAsubT8, y = ciliated)
seurat_obj <- SetIdent(seurat_obj,value = "cellchat")
```

```{r}
data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
identity <- subset(seurat_obj@meta.data, select = "cellchat")
cellchat <- createCellChat(object = data.input, meta = identity,  group.by = "cellchat")
CellChatDB <- CellChatDB.human
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 10)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)

cellchat <- setIdent(cellchat, ident.use = "cellchat", 
                     levels = c("T8_naive","T8_cm","T8_em","T8_rm","T8_emra/eff",
                                "T8_NK-like","Cycling","MAIT", "BALF Ciliated Epi"))

cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
groupSize <- as.numeric(table(cellchat@idents))


```

```{r}
saveRDS(cellchat, file = "cellchat/cellchat_BALF-ciliated_T8.rds")
```

```{r}
rm(list = ls())
gc()
```
