---
title: "Figure 1"
author: "YueanZhao"
output: html_document
---

```{r}
scRNA <- readRDS("rds/scRNA_46_anno.rds")
DefaultAssay(scRNA) <- "RNA"
```

```{r}
scRNA$cell_type <- factor(scRNA$cell_type, levels = order_celltype)
scRNA$cell_type_main <- factor(scRNA$cell_type_main, levels = order_celltype_main)
scRNA$orig.ident <- factor(scRNA$orig.ident,levels = order_origID)
scRNA$disease<- factor(scRNA$disease, levels = order_disease)
```

# fig1c DimPlot
```{r}
p = DimPlot(scRNA, group.by = "cell_type", cols = color_celltype, raster = F)+NoLegend()+theme_blank
ggsave("fig1/1c_DimPlot.png",p, width = 7,height = 7)
ggsave("fig1/1c_DimPlot.pdf",p, width = 7,height = 7)
```

```{r}
p = DimPlot(scRNA, group.by = "cell_type", cols = color_celltype, raster = F)
l =as_ggplot(get_legend(p)) 
ggsave("fig1/1c_DimPlot_legend.pdf",l)
```

# fig1d stacked bar prop
```{r}
Ratio <- scRNA@meta.data %>%
  group_by(sample_type, cell_type) %>% 
  summarise(n=n()) %>%
  mutate(relative_freq = n/sum(n))
         
p = ggplot(Ratio,aes(x=sample_type,y= relative_freq,
                    fill=cell_type,stratum=cell_type, alluvium=cell_type))+
    geom_col(width = 0.5, color='black',size = 0.25)+
    xlab(NULL)+ylab("Celltype Percentage")+
    scale_fill_manual(values =color_celltype)+
    scale_x_discrete(limits = c("BALF","Lung","PBMC"))+
    theme_cowplot()+
    geom_flow(width=0.5,alpha=0.4, knot.pos=0.5)+
    theme(axis.text.x = element_text(angle = 45,hjust =1, vjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.key.width  = unit(0.1,"in"),legend.key.height   = unit(0.1,"in"))
ggsave("fig1/1d_prop_celltype_sampletype.pdf",p,width = 4, height = 4)
```

# fig1e lung prop
```{r}
lung <- scRNA[,scRNA$sample_type == "Lung" & scRNA$patient != "C2"]

df_tobesummed_main = data.frame(orig.ident = lung$orig.ident, group = lung$disease, 
                                cell_type = lung$cell_type_main)
df_summed_main = df_tobesummed_main %>% group_by(orig.ident, cell_type, group) %>% tally()
df_summed_main = df_summed_main %>% group_by(orig.ident) %>% mutate(freq = n/sum(n))

stat.test <- df_summed_main%>% group_by(cell_type) %>% wilcox_test(freq ~ group) %>%add_significance()%>% add_xy_position(x = "cell_type")

p = ggboxplot(df_summed_main, x = "cell_type", y = "freq",color = "group", add = "jitter",
              palette = color_disease,width = 0.6,
              add.params = list( color = "group", size = 2)) + 
    ylim(0, 0.85) + 
    stat_pvalue_manual(stat.test, label = "p.signif",hide.ns =T) +
    xlab(NULL)+ylab("Fraction of Cells in Lung")+
    theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1),,
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
          plot.title = element_text(hjust = 0.5),legend.position = "right")
ggsave("fig1/1e_box_prop_celltype_main.pdf", plot = p, width = 6 , height = 4)
```

# fig1f density
```{r}
lung <- scRNA[,scRNA$sample_type == "Lung" & scRNA$patient != "C2"]

umap = lung@reductions$umap@cell.embeddings %>% 
       as.data.frame() %>% 
       cbind(disease = lung@meta.data$disease)

p = ggplot(data = umap, mapping = aes(x = UMAP_1,y = UMAP_2)) + 
    facet_wrap(~disease, nrow = 1) +
    geom_pointdensity(adjust= 0.5) +
    scale_color_gradientn(colors = c("#FBF9C1", "#FFC30F", "#FF5744", "#C70039", "#900C3F", "#581845"))+
    theme_cowplot() + theme_blank +
    theme(strip.text = element_blank(),strip.background  = element_blank())+
    NoLegend()

ggsave("fig1/1f_density_disease.png",p,width = 6, height = 3)
ggsave("fig1/1f_density_disease.pdf",p,width = 6, height = 3)
```

```{r}
p = ggplot(data = umap, mapping = aes(x = UMAP_1,y = UMAP_2)) + 
    facet_wrap(~disease, nrow = 2) +
    geom_pointdensity(adjust= 0.5) +
    scale_color_gradientn(colors = c("#FBF9C1", "#FFC30F", "#FF5744", "#C70039", "#900C3F", "#581845"))
l =as_ggplot(get_legend(p)) 
ggsave("fig1/1f_density_disease_legend.pdf",l)
```
