---
title: "Figure S1"
author: "YueanZhao"
output: html_document
---
```{r}
scRNA <- readRDS("rds/scRNA_46_anno.rds")
DefaultAssay(scRNA) <- "RNA"
```

```{r}
scRNA$cell_type <- factor(scRNA$cell_type, levels = order_celltype)
scRNA$cell_type_main <- factor(scRNA$cell_type_main, levels = order_celltype_main)
scRNA$orig.ident_ID <- factor(scRNA$orig.ident,levels = order_origID)
scRNA$disease<- factor(scRNA$disease, levels = order_disease)
```


# figS1c Featureplot
```{r}
scRNA <- SetIdent(scRNA,value = "cell_type")
DefaultAssay(scRNA) <- "RNA"
all.markers <- FindAllMarkers(scRNA, 
                              only.pos = TRUE, test.use = "MAST",
                              min.pct = 0.25, logfc.threshold = 0.5)
top10 = all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
write.csv(all.markers, "sTable/s1c_all_markers_all_MAST.csv", row.names = F)
write.csv(top10, "sTable/s1c_top10_markers_all_MAST.csv", row.names = F)
```


```{r}
DefaultAssay(scRNA) <- "RNA"
markergene <- c("CD3E","CD4","CD8A","NKG7","MKI67","MS4A1","JCHAIN","MARCO","LYZ","FCGR3B",
                 "FCGR3A","CAPS","AGER","SFTPC","FOXP3","COL1A1",
                 "PPBP","TPSAB1","CDH5","FCER1A","ITM2C")

plot.list <- lapply(X = markergene, FUN = function(x) {
    FeaturePlot(scRNA ,cols = beach, features = x, raster = F,order = T)+
    NoLegend()+
    theme(axis.title=element_blank(),axis.text=element_blank(),
          axis.ticks=element_blank(),axis.line=element_blank(),
          plot.title = element_text(vjust = -2, size = rel(2.5)))
})

p <- wrap_plots(plots = plot.list, nrow=3)    
ggsave("figS1/S1c_featureplot.png", plot = p, width = 35 , height = 15) 

#plot the legend
p = FeaturePlot(scRNA,cols = beach, features = "CD3E", raster = F)
l=as_ggplot(get_legend(p)) 
ggsave('figS1/S1c_featureplot_Legend.pdf', l)
```

# figS1d piled cell num bar
```{r}
clusters <- data.frame(table(scRNA$cell_type, scRNA$orig.ident))
colnames(clusters)[[2]]<-"orig.ident"

p =ggplot(clusters) + 
  geom_bar(aes(x =Var1, y= Freq, fill = orig.ident),stat = "identity",width = 0.7)+ 
  labs(x=NULL,y = 'Number of Cells')+
  theme_cowplot()+
  scale_fill_manual(values=color_origID, limits = order_origID)+
  theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1,size = rel(1)),
        axis.text = element_text(size = 14),axis.title = element_text(size = 16))+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))+NoLegend()
ggsave("figS1/S1d_celltype_orig_num.pdf",p,width = 6, height = 5)
```

```{r}
p =ggplot(clusters) + 
  geom_bar(aes(x =Var1, y= Freq, fill = orig.ident),stat = "identity",width = 0.7)+ 
  scale_fill_manual(values=color_origID, limits = order_origID)+
  guides(fill = guide_legend(title = 'orig.ident',
                             direction = "vertical",
                             keywidth = 0.5,keyheight = 0.5,
                             label.theme = element_text(size = 6),
                             ncol = 4,byrow = T))+
  theme(legend.spacing.x = unit(0.02,'in'),legend.spacing.y = unit(0.02,'in'),
        legend.title = element_text(size = 7))
  
l=as_ggplot(get_legend(p)) 
ggsave('figS1/S1d_celltype_orig_num_legend.pdf', l, width = 4,height = 3)
```

# figS1e neutro prop

```{r}
scRNAsub <- scRNA[,scRNA$sample_type %in% c("Lung","BALF") & scRNA$disease %in% "Pneumonia"]
df = data.frame(orig.ident = scRNAsub$orig.ident, group = scRNAsub$bacterial, 
                cell_type = scRNAsub$cell_type, sample_type = scRNAsub$sample_type)
df_summed = df %>% group_by(orig.ident, cell_type, group,sample_type) %>% tally()
df_summed = df_summed %>% group_by(orig.ident) %>% mutate(freq = n/sum(n))
df_summed = df_summed[df_summed$cell_type == "Neutrophils",]
```

```{r}
stat.test <- df_summed %>% group_by(cell_type,sample_type) %>% wilcox_test(freq ~ group) %>%add_significance()%>% add_xy_position(x = "group")
```

```{r}
p = ggboxplot(data.frame(df_summed),x = "group", y = "freq",add = "jitter",alpha = 0.7,
            fill = "group",order = c("bacterial",'non-bacterial'),
            add.params = list(fill = df_summed$orig.ident, color="orig.ident", size = 3),
            palette = c(color_origID,color_infection)) + 
    stat_pvalue_manual(stat.test, label = "p.signif",hide.ns =F) +
    facet_wrap(~sample_type)+
    theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1),
          plot.title = element_text(hjust = 0.5),legend.position = "right",
          axis.text = element_text(size = 14),axis.title = element_text(size = 16),
          legend.title = element_text(size = 14),legend.text = element_text(size = 12),
          strip.text = element_text(size = 14))+
    xlab(NULL)+ylab("Neutrophils Fraction")
ggsave("figS1/S1e_neutro_prop_lung&balf.pdf", plot = p, width = 5 , height = 5)
```


# figS1f pbmc prop
```{r}
pbmc <- scRNA[,scRNA$sample_type == "PBMC" & scRNA$patient != "C2"]

df_tobesummed_main = data.frame(orig.ident = pbmc$orig.ident, group = pbmc$disease, 
                                cell_type = pbmc$cell_type_main)
df_summed_main = df_tobesummed_main %>% group_by(orig.ident, cell_type, group) %>% tally()
df_summed_main = df_summed_main %>% group_by(orig.ident) %>% mutate(freq = n/sum(n))

stat.test <- df_summed_main%>% group_by(cell_type) %>% wilcox_test(freq ~ group) %>%add_significance()%>% add_xy_position(x = "cell_type")

p = ggboxplot(df_summed_main, x = "cell_type", y = "freq",color = "group", add = "jitter",
              palette = color_disease,width = 0.6,
              add.params = list( color = "group", size = 2)) + 
    ylim(0, 0.9) + 
    stat_pvalue_manual(stat.test, label = "p.signif",hide.ns =T) +
    xlab(NULL)+ylab("Fraction of Cells in PBMC")+
    theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1),
          plot.title = element_text(hjust = 0.5),legend.position = c(0.8,0.8),
          axis.text = element_text(size = 14),axis.title = element_text(size = 16),
          legend.title = element_text(size = 14),legend.text = element_text(size = 12))
ggsave("figS1/S1f_box_prop_celltype_main_PBMC.pdf", plot = p, width = 6 , height = 5)
```

