---
title: "Figure S4"
author: "YueanZhao"
output: html_document
---

```{r}
rm(list = ls())
gc()
```

# S4a P6 viral loadsplt by sample
```{r}
scRNA_P6 <- readRDS("rds/scRNA_P6_fluB.rds")
scRNA_P6$cell_type <- factor(scRNA_P6$cell_type, levels = order_celltype)
```


```{r}
md <- cbind(scRNA_P6[["fluB"]],
            scRNA_P6[["sample_type"]],
            Embeddings(scRNA_P6[["umap"]]))

p = ggplot(md[!is.na(md$fluB),], 
           aes(x = UMAP_1, y = UMAP_2, color = fluB))+
  geom_point(data = md[is.na(md$fluB),], color = "lightgrey", size = 1)  + 
  geom_point(shape = 16,size = 5)  +
  scale_color_gradientn(colors = rev(brewer.pal(9,"Spectral")))+
  facet_wrap(~ sample_type)+
  theme_cowplot()+theme_blank + NoLegend()+
  theme(strip.background = element_blank(),strip.text = element_blank())

ggsave("figS4/s4a_P6_fluload_DimPlot_spilt.by.sample.png",p,width = 12, height = 4)
```

```{r}
p = ggplot(md[!is.na(md$fluB),], 
           aes(x = UMAP_1, y = UMAP_2, color = fluB))+
  geom_point(data = md[is.na(md$fluB),], color = "lightgrey", size = 1)  + 
  geom_point(shape = 16,size = 3)  +
  scale_color_gradientn(colors = rev(brewer.pal(9,"Spectral")))+
  facet_wrap(~ sample_type)+
  theme_cowplot()+theme_blank 
l =as_ggplot(get_legend(p)) 
ggsave("figS4/s4a_P6_fluload_DimPlot_spilt.by.sample_legend.pdf",l)
```

# S4b GO fluB vs noflu
```{r}
scRNA_P6[["group_flu"]] <- ifelse(is.na(scRNA_P6$fluB),
                                  scRNA_P6[["group_flu"]]<-"no fluB",
                                  scRNA_P6[["group_flu"]]<-"fluB")
DefaultAssay(scRNA_P6) <- "RNA"
```

```{r}
DEG <- FindMarkers(scRNA_P6,
                   group.by = "group_flu",
                   ident.1 = "fluB", ident.2 = "no fluB",
                   test.use = "MAST")
write.csv(DEG, "sTable/s4b_DEG_P6_fluB.vs.nofluB.csv")
```

```{r}
filtered_DEG_up <- subset(DEG,DEG$avg_log2FC > 1)
DEG_ego_BP_up <- data.frame(enrichGO(gene = row.names(filtered_DEG_up),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_up,'sTable/s4b_GO_BP_P6_fluB.vs.nofluB_up.csv') 

DEG_ego_BP_up$change <- c("up") 

DEG_ego_BP_up <- DEG_ego_BP_up[order(DEG_ego_BP_up$qvalue),]
DEG_ego_BP_up_top15 <- DEG_ego_BP_up[1 : 15,]
DEG_ego_BP_up_top15$Description <- factor(DEG_ego_BP_up_top15$Description,
                                          levels = rev(DEG_ego_BP_up_top15$Description))
```


```{r}
p <- ggplot(data = DEG_ego_BP_up_top15,
            aes(x = Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Reds",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_y_discrete(position = "left")+
  scale_x_continuous(expand = c(0,0))+ylab(NULL)+ggtitle("w/ Influenza B Virus")+
  theme_bw() +theme_GO+  
  theme(plot.title =  element_text(hjust = 0.5,face = "bold",colour = "black"),
        legend.position = "top")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size = unit(0.15,"in"))

ggsave("figS4/s4b_P6_fluB.vs.nofluB_GO.pdf",p,width = 5,height = 4)
```

# S4c HLA VlnPlot fluB vs nofluB
```{r}
scRNA_P6 <- SetIdent(scRNA_P6,value = "group_flu")
p1 = VlnPlot(scRNA_P6, 
            features = c("HLA-A","GBP1","IL1RN","CCRL2"), 
            cols = c("#b2182b","#2166ac"),
            group.by = "group_flu",
            pt.size = 0,assay = 'RNA',split.by = "group_flu",stack =T,flip = T)+
  NoLegend()+
  xlab(NULL)+
  theme(axis.text.x  = element_text(angle = 45,hjust =1, vjust = 1),
        strip.text = element_text(face = "plain",size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))
p2 = VlnPlot(scRNA_P6, 
            features = c("JUN","IRF1","TLR2","SOD2"), 
            cols = c("#b2182b","#2166ac"),
            group.by = "group_flu",
            pt.size = 0,assay = 'RNA',split.by = "group_flu",stack =T,flip = T)+
  NoLegend()+
  xlab(NULL)+ylab(NULL)+
  theme(axis.text.x  = element_text(angle = 45,hjust =1, vjust = 1),
        strip.text = element_text(face = "plain",size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))
p = p1+p2
ggsave('figS4/s4c_Vlnplot_flu.pdf',p,height=4,width=4)
```

# S4d 4TCR DimPlot
```{r}
scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
```

```{r}
md <- cbind(scRNAsubT8[["TCR_ID"]],
            scRNAsubT8[["sample_type"]],
            Embeddings(scRNAsubT8[["umap"]]))

p = ggplot(md[md$TCR_ID %in% c("P6_T_1","P6_T_10","P6_T_6","P6_T_9"),], 
           aes(x = UMAP_1, y = UMAP_2, color = TCR_ID))+
  geom_point(data = md[!(md$TCR_ID %in% c("P6_T_1","P6_T_10","P6_T_6","P6_T_9")),],
             color = "lightgrey", size = 1)  + 
  geom_point(shape = 16,size = 3)  +
  scale_color_manual(values = color_P6_TCR)+
  facet_wrap(~ sample_type, nrow = 3)+
  theme_cowplot()+theme_blank + NoLegend()+
  theme(strip.background = element_blank(),strip.text = element_blank())
ggsave("figS4/s4d_P6_4TCR_DimPlot_spilt.by.sample.png",p,width = 4, height = 12)
```

```{r}
p = ggplot(md[md$TCR_ID %in% c("P6_T_1","P6_T_10","P6_T_6","P6_T_9"),], 
           aes(x = UMAP_1, y = UMAP_2, color = TCR_ID))+
  geom_point(data = md[!(md$TCR_ID %in% c("P6_T_1","P6_T_10","P6_T_6","P6_T_9")),],
             color = "lightgrey", size = 1)  + 
  geom_point(shape = 16,size = 3)  +
  scale_color_manual(values = color_P6_TCR)+theme_cowplot()+theme_blank
l =as_ggplot(get_legend(p)) 
ggsave("figS4/s4d_P6_4TCR_DimPlot_spilt.by.sample_legend.pdf",l)
```

```{r}
disease_pattern <- readRDS("rds/T8_disease_TCRpattern.rds")
seurat_obj <- disease_pattern[,disease_pattern$TCR_ID %in% c("P6_T_1","P6_T_10","P6_T_6","P6_T_9")]
DefaultAssay(seurat_obj) <- "RNA"
DEG <- FindMarkers(seurat_obj,
                   group.by = "pattern",
                   ident.1 = "pattern 1a", ident.2 = "pattern 2",
                   test.use = "MAST")
genes <- rownames(subset(DEG,DEG$avg_log2FC > 1.5 | DEG$avg_log2FC < -1.5))
gene_selected <- setdiff(genes,genes[c(grep("TRGV",genes),grep("TRBV",genes),
                                       grep("TRAV",genes),grep("TRBC",genes),
                                       grep("MT-",genes),grep("IGKV",genes),grep("HIST",genes))])

gene_selected <-c(gene_selected, "HLA-A")

seurat_obj <- SetIdent(seurat_obj,value = "TCR_ID")
gene_selected <- intersect(gene_selected, rownames(GetAssayData(seurat_obj, slot = 'data')))
mat <- AverageExpression(seurat_obj, features = gene_selected, slot = 'data',assays = "RNA")
mat1 <- scale(t(mat$RNA))

p = Heatmap(mat1, name = "avg_Exp", cluster_rows = T, cluster_columns = T,
            col = colorRamp2(c(-2, 0, 2), c("#2166ac","white","#b2182b")),
            column_names_rot = 45)
pdf("figS4/s4d_4TCR_DEG&HLA_heatmap_P6.pdf",width=12,height=3)
draw(p)
dev.off()
```


# S4e cellchat incoming/outgoing
```{r}
cellchat <- readRDS("cellchat/cellchat_flu_P6T1&6&9&10_MHCI.rds")
```

```{r}
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
```

```{r}
pdf("figS4/s4e_cellchat_pattern_outgoing.pdf", width=10, height=10)
identifyCommunicationPatterns(cellchat,pattern = "outgoing",k = 3,
                              heatmap.show = T,
                              color.heatmap = "RdYlBu",
                              color.use = c("#F55353","#34A047","#74C476","#FCBF6E","#F47E1F"),
                              width = 4,height =6,font.size = 11)
dev.off()

pdf("figS4/s4e_cellchat_pattern_incoming.pdf", width=10, height=10)
identifyCommunicationPatterns(cellchat,pattern = "incoming",k = 3,
                              heatmap.show = T,
                              color.heatmap = "RdYlBu",
                              color.use = c("#F55353","#34A047","#74C476","#FCBF6E","#F47E1F"),
                              width = 4,height =6,font.size = 11)
dev.off()
```

# S4f cellchat bubble

```{r}
pdf("figS4/s4f_cellchat_bubble.pdf", width=5, height=9)
netVisual_bubble(cellchat, sources.use = 5, targets.use = c(1:4), remove.isolate = FALSE,
                 angle.x = 45,font.size = 15,font.size.title = 15,line.size = 0.4)+
  theme(legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))
dev.off()
```

# S4g P6 TCR heatmap
drawn in fig4

