---
title: "Figure S2"
author: "YueanZhao"
output: html_document
---
```{r}
rm(list = ls())
gc()
```

# T&NK
## rds & palette
```{r}
scRNAsubT <- readRDS("rds/scRNAsubT&NK_anno_TCRID.rds")
DefaultAssay(scRNAsubT) <- "RNA"
```

```{r}
scRNAsubT$cell_type_main <- factor(scRNAsubT$cell_type_main, levels =order_T)
```

## s2a T&NK Dimplot
```{r}
p = DimPlot(scRNAsubT, group.by = "cell_type_main",
            cols = color_T, raster = F, label = F) + NoLegend() + theme_blank
ggsave("figS2/s2a_T&NK_DimPlot.png",p,width = 5,height = 5)
```

```{r}
p=DimPlot(scRNAsubT, group.by = "cell_type_main",cols = color_T, raster = F, label = F)+theme_blank
l=as_ggplot(get_legend(p)) 
ggsave('figS2/s2a_T&NK_DimPlot_legend.pdf', l)
```

## s2b T&NK FeaturePlot
```{r}
DefaultAssay(scRNAsubT) <- "RNA"
markergene_T <- c("CD3E","CD8A","CD4","TYROBP","TRDV2","SLC4A10",
                  "MKI67","SELL","NKG7","GZMK","ITGAE","FOXP3")
plot.list <- lapply(X = markergene_T, FUN = function(x) {
  FeaturePlot(scRNAsubT ,
              cols = greyMagma, 
              features = x, raster = F)+
    NoLegend()+theme_blank+labs(NULL)+
    theme(plot.title = element_blank())
})
p <- wrap_plots(plots = plot.list, nrow=2)    
ggsave("figS2/s2b_T&NK_featureplot.png", plot = p, width = 30 , height = 10) 
```

```{r}
p = FeaturePlot(scRNAsubT,features="CD3E",cols = greyMagma,raster = F) + 
    theme_blank
l =as_ggplot(get_legend(p)) 
ggsave("figS2/s2b_T&NK_FeaturePlot_legend.pdf",l)
```

# T8
## rds & palette
```{r}
scRNAsubT8 <- readRDS("rds/scRNAsubT8_anno_TCRpercent_Cycling.NoCD4.rds")
DefaultAssay(scRNAsubT8) <- "RNA"

scRNAsubT8$cell_type <- factor(scRNAsubT8$cell_type, levels = order_T8)
scRNAsubT8$cell_type_main <- factor(scRNAsubT8$cell_type_main, levels = order_T8_main)
scRNAsubT8$orig.ident <- factor(scRNAsubT8$orig.ident,levels = order_origID)
scRNAsubT8$disease<- factor(scRNAsubT8$disease, levels =c("Pneumonia","Ctrl"))
```

## s2c T8 DotPlot

```{r}
scRNAsubT8 <- SetIdent(scRNAsubT8,value = "cell_type_main")
DefaultAssay(scRNAsubT8) <- "RNA"
T8.all.markers <- FindAllMarkers(scRNAsubT8, 
                              only.pos = TRUE, test.use = "MAST",
                              min.pct = 0.25, logfc.threshold = 0.5)
T8.top10 = T8.all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
write.csv(T8.all.markers, "sTable/s2c_all_markers_T8_MAST.csv", row.names = F)
write.csv(T8.top10, "sTable/s2c_top10_markers_T8_MAST.csv", row.names = F)
```

```{r}
markergene_T8 = c("CCR7","TCF7","SELL", 
                "LTB","NELL2","IL7R", 
                "GZMK","EOMES","CCL4L2", 
                "FGFBP2","CX3CR1","GNLY", 
                "KLRC2","TYROBP","IKZF2", 
                "ZNF683","ITGAE","CXCR6", 
                "STMN1","MKI67","TUBB", 
                "SLC4A10","TRAV1-2","CEBPD" 
                )
DefaultAssay(scRNAsubT8) <- "RNA"
p = DotPlot(scRNAsubT8, group.by = "cell_type_main",features = markergene_T8) +
    scale_colour_gradientn(colors=brewer.pal(9, "RdPu")) +
    theme(axis.text.x = element_text(angle = 45,hjust = 1,vjust = 1),
          axis.text = element_text(size = 16),
          axis.title = element_text(size = 16),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 14)) +
    xlab(NULL) + ylab(NULL)
ggsave('figS2/s2c_T8_Dotplot.pdf', p, width = 10, height = 4)
```

## s2d pbmc prop
```{r}
pbmc <- scRNAsubT8[,scRNAsubT8$sample_type == "PBMC" & scRNAsubT8$patient != "C2"]

df_tobesummed_main = data.frame(orig.ident = pbmc$orig.ident, group = pbmc$disease, 
                                cell_type = pbmc$cell_type_main)
df_summed_main = df_tobesummed_main %>% group_by(orig.ident, cell_type, group) %>% tally()
df_summed_main = df_summed_main %>% group_by(orig.ident) %>% mutate(freq = n/sum(n))

stat.test <- df_summed_main%>% group_by(cell_type) %>% wilcox_test(freq ~ group) %>%add_significance()%>% add_xy_position(x = "cell_type")

p = ggboxplot(df_summed_main, x = "cell_type", y = "freq",color = "group", add = "jitter",
              palette = color_disease,width = 0.6,
              add.params = list( color = "group", size = 2)) + 
    ylim(0, 0.6) + 
    stat_pvalue_manual(stat.test, label = "p.signif",hide.ns =T) +
    xlab(NULL)+ylab("Fraction of T8 Cells in PBMC")+
    theme(axis.text.x = element_text(angle = 45,hjust = 1,vjust = 1),
          axis.text = element_text(size = 16),
          axis.title = element_text(size = 16),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 16),
          legend.position = "right")
ggsave("figS2/s2d_box_prop_celltype_main_PBMC.pdf", plot = p, width = 7 , height = 4)
```

## s2e T8 rm DEG GO enrichment
```{r}
scRNArm <- scRNAsubT8[,scRNAsubT8$cell_type_main %in% c("T8_rm")]
scRNArm <- scRNArm[,!(scRNArm$patient %in% "C2")]
DEG <- FindMarkers(scRNArm,group.by = "disease",ident.1 = "Pneumonia", ident.2 = "Ctrl",test.use = "MAST")
write.csv(DEG, "sTable/s2e_DEG_T8_rm_Disease_vs_Ctrl.csv")
```

```{r}
filtered_DEG_up <- subset(DEG,DEG$avg_log2FC > 0.5)
DEG_ego_BP_up <- data.frame(enrichGO(gene = row.names(filtered_DEG_up),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_up,'sTable/s2e_GO_BP_up_T8rm_Disease_vs_Ctrl.csv') 

filtered_DEG_down <- subset(DEG,DEG$avg_log2FC < -0.5)
DEG_ego_BP_down <- data.frame(enrichGO(gene = row.names(filtered_DEG_down),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_down,'sTable/s2e_GO_BP_down_T8rm_Disease_vs_Ctrl.csv') 


DEG_ego_BP_up$change <- c("up") 
DEG_ego_BP_down$change <- c("down") 

DEG_ego_BP_up <- DEG_ego_BP_up[order(DEG_ego_BP_up$qvalue),]
DEG_ego_BP_up_top15 <- DEG_ego_BP_up[1 : 15,]
DEG_ego_BP_up_top15$Description <- factor(DEG_ego_BP_up_top15$Description,
                                          levels = rev(DEG_ego_BP_up_top15$Description))

DEG_ego_BP_down <- DEG_ego_BP_down[order(DEG_ego_BP_down$qvalue),]
DEG_ego_BP_down_top15 <- DEG_ego_BP_down[1 : 15,]
DEG_ego_BP_down_top15$Description <- factor(DEG_ego_BP_down_top15$Description,
                                            levels = rev(DEG_ego_BP_down_top15$Description))
```


```{r}
p1 <- ggplot(data = DEG_ego_BP_up_top15,
            aes(x = Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Reds",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_y_discrete(position = "right")+
  scale_x_continuous(expand = c(0,0))+ylab(NULL)+ggtitle("Pneumonia")+
  theme_bw() +theme_GO+  
  theme(plot.title =  element_text(hjust = 0.5,size = rel(1.5),face = "bold",colour = "black"),
        legend.position = "top")+
  theme(axis.text = element_text(size = 16), axis.title = element_text(size = 16),
        legend.title = element_text(size = 16),legend.text = element_text(size = 16))


p2 <- ggplot(data = DEG_ego_BP_down_top15,
            aes(x = -Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Blues",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_x_continuous(expand = c(0,0),breaks = c(-15,-10, -5,0),label = c("15","10", "5","0"))+
  theme_bw() +theme_GO+theme(legend.position = "left")+xlab("Count")+ggtitle("Ctrl")+
  theme(plot.title =  element_text(hjust = 0.5,size = rel(1.5),face = "bold",colour = "black"),
        legend.position = "top")+
  theme(axis.text = element_text(size = 16), axis.title = element_text(size = 16),
        legend.title = element_text(size = 16),legend.text = element_text(size = 16))

p= p2+p1
  
ggsave("figS2/s2e_T8rm_GO_DvsC.pdf",p,width = 20,height = 6)
```


# T4
## rds & palette
```{r}
scRNAsubT4 <- readRDS("rds/scRNAsubT4_anno_TCRID_Cycling.NoCD8A.rds")
DefaultAssay(scRNAsubT4) <- "RNA"
```

```{r}
scRNAsubT4$cell_type_main<- factor(scRNAsubT4$cell_type_main, levels = order_T4)
scRNAsubT4$disease<- factor(scRNAsubT4$disease, levels = order_disease)
```

## s2f T4 DimPlot

```{r}
p = DimPlot(scRNAsubT4, group.by = "cell_type_main",cols = color_T4,label = F) + 
    theme_cowplot() + theme_blank + NoLegend()
ggsave("figS2/s2f_T4_DimPlot.png",p, width = 5, height = 5)
```

```{r}
#plot the legend
p=DimPlot(scRNAsubT4, group.by = "cell_type_main",cols = color_T4)+theme_blank
l=as_ggplot(get_legend(p)) 
ggsave('figS2/s2f_T4_DimPlot_legend.pdf', l)
```

## s2g T4 DotPlot
```{r}
scRNAsubT4 <- SetIdent(scRNAsubT4,value = "cell_type_main")
DefaultAssay(scRNAsubT4) <- "RNA"
T4.all.markers <- FindAllMarkers(scRNAsubT4, 
                              only.pos = TRUE, test.use = "MAST",
                              min.pct = 0.25, logfc.threshold = 0.5)
T4.top10 = T4.all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
write.csv(T4.all.markers, "sTable/s2g_all_markers_T4_MAST.csv", row.names = F)
write.csv(T4.top10, "sTable/s2g_top10_markers_T4_MAST.csv", row.names = F)
```

```{r}
markergene_T4 = c("CCR7","LEF1","SELL", 
                "IKZF2","FOXP3","TIGIT",
                "FAAH2","INPP4B","ANK3",
                "ITM2A","COTL1","ITGA4",
                "FOS","CXCR3","RBPJ",
                "CCR6","AQP3","KLRB1", 
                "PI16","CRIP2","GATA3",
                "GNLY","GZMH","CX3CR1",
                "STMN1","MKI67","TUBB"
                )
DefaultAssay(scRNAsubT4) <- "RNA"
p = DotPlot(scRNAsubT4, group.by = "cell_type_main",features = markergene_T4) +
    scale_colour_gradientn(colors=brewer.pal(9, "BuPu")) +
    theme(axis.text.x = element_text(angle = 45,hjust = 1,vjust = 1),
          axis.text = element_text(size = 16),
          legend.text = element_text(size = 16),
          legend.direction = "horizontal",legend.position = "top") +
    xlab(NULL) + ylab(NULL)
ggsave('figS2/s2g_T4_Dotplot.pdf', p, width = 10, height = 5)
```

## s2h T4 stacked barplot disease by sample type
```{r}
disease <- scRNAsubT4[,scRNAsubT4$disease == "Pneumonia"]
```

```{r}
Ratio <- disease@meta.data %>%
  group_by(sample_type, cell_type_main) %>% 
  summarise(n=n()) %>%
  mutate(relative_freq = n/sum(n))
         
p= ggplot(Ratio,aes(x=sample_type,y= relative_freq,
                    fill=cell_type_main,stratum=cell_type_main, alluvium=cell_type_main))+
  geom_col(width = 0.5, color='black',size = 0.25)+
  xlab(NULL)+ylab("T4 Pneumonia Celltype Percentage")+
  scale_fill_manual(values =color_T4)+
  geom_flow(width=0.5,alpha=0.4, knot.pos=0.5)+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust =1, vjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 14))

ggsave("figS2/s2h_T4_prop_celltype_sampletype.pdf",p,width = 4, height = 5)
```

## s2i T4 split DimPlot by disease
```{r}
p = DimPlot(scRNAsubT4, group.by = "cell_type_main",split.by = "disease",cols = color_T4,label = F) + 
    theme_cowplot() + theme_blank + NoLegend() +
  theme(strip.background = element_blank(),strip.text = element_blank())
ggsave("figS2/s2i_T4_splt.disease_DimPlot.png",p, width = 10, height = 5)
```

## s2j T4 density: disease facet by sample type

```{r}
umap = disease@reductions$umap@cell.embeddings %>% 
       as.data.frame() %>% 
       cbind(sample_type = disease@meta.data$sample_type)

p = ggplot(data = umap, mapping = aes(x = UMAP_1,y = UMAP_2)) + 
    facet_wrap(~sample_type, nrow = 1) +
    geom_pointdensity(adjust= 0.5) +
    scale_color_gradientn(colors = rev(c("#581845", "#900C3F","#C70039","#FF5744","#FFC30F","#FBF9C1")))+
    theme_cowplot() + 
    theme(axis.title=element_blank(),axis.text=element_blank(),
                     axis.ticks=element_blank(),axis.line=element_blank(),
                     plot.title=element_text(hjust = 0.5),
          strip.text = element_blank(),strip.background = element_blank())+
    NoLegend()

ggsave("figS2/s2j_T4_density_disease_sampletype.png",p,width = 15, height = 5)
```

```{r}
p = ggplot(data = umap, mapping = aes(x = UMAP_1,y = UMAP_2)) + 
    facet_wrap(~sample_type, nrow = 1) +
    geom_pointdensity(adjust= 0.5) +
    scale_color_gradientn(colors = rev(c("#581845", "#900C3F","#C70039","#FF5744","#FFC30F","#FBF9C1")))

l =as_ggplot(get_legend(p)) 
ggsave("figS2/s2j_T4_density_disease_sampletype_legend.pdf",l)
```


