---
title: "Figure S3"
author: "YueanZhao"
output: html_document
---
```{r}
rm(list = ls())
gc()
```

```{r}
scRNAsubT <- readRDS("rds/scRNAsubT&NK_anno_TCRID.rds")
DefaultAssay(scRNAsubT) <- "RNA"
```

```{r}
scRNAsubT$cell_type_main <- factor(scRNAsubT$cell_type_main, levels =order_T)
scRNAsubT$TCR_clonetype <- factor(scRNAsubT$TCR_clonetype, levels =order_TCR_clonetype)
```


# s3a T&NK TCR clonetype DimPlot

```{r}
scRNA <- scRNAsubT[,scRNAsubT$patient != "C2"]
md <- cbind(Embeddings(scRNA[["umap"]]),scRNA[["TCR_clonetype"]],scRNA[["disease"]])

p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Pneumonia",], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Pneumonia",],shape = 16,size = 1,alpha = 0.8)  +
  scale_color_manual(values = color_TCR_clonetype_disease)+
  labs(colour = "Pneumonia")+
  theme_cowplot()+
  theme_blank+NoLegend()

ggsave("figS3/s3a_DimPlot_T&NK_clonetype_disease.png",p, width = 5, height = 5)
```


```{r}
p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Ctrl",], color = "lightgrey", size = 1)  +
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"),
             shape = 16,size = 1,alpha = 0.8) +
  scale_color_manual(values = color_TCR_clonetype_ctrl)+
  labs(colour = "ctrl")+
  theme_cowplot()+
  theme_blank+NoLegend()
ggsave("figS3/s3a_DimPlot_T&NK_clonetype_ctrl.png",p, width = 5, height = 5)
```

```{r}
p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Pneumonia",], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Pneumonia",],shape = 16,size = 1,alpha = 0.8)  +
  scale_color_manual(values = color_TCR_clonetype_disease,
                     breaks = rev(order_TCR_clonetype))+
  labs(colour = "Pneumonia")+new_scale("color")+
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"),
             shape = 16,size = 1,alpha = 0.8) +
  scale_color_manual(values = color_TCR_clonetype_ctrl,
                     breaks = rev(order_TCR_clonetype))+
  labs(colour = "Ctrl")+
  theme_cowplot()+
  theme_blank
l=as_ggplot(get_legend(p)) 
ggsave('figS3/s3a_DimPlot_T&NK_clonetype_legend.pdf', l)
```

# s3b T&NK clonetype expansion
```{r}
clusters <- data.frame(table(scRNA$TCR_clonetype, scRNA$disease,scRNA$cell_type_main))
colnames(clusters)[1:3]<- c("TCR_clonetype","group","cell_type")
clusters <- clusters[order(clusters$cell_type,clusters$group,clusters$TCR_clonetype),]

p = ggplot(clusters) + 
  geom_bar(data = clusters[clusters$group == "Pneumonia",],
           aes(x =cell_type, y= Freq, fill = TCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 1) + 
  scale_fill_manual(values=color_TCR_clonetype_disease,
                    breaks = rev(order_TCR_clonetype))+
  labs(fill = "Pneumonia")+new_scale("fill")+
  geom_bar(data = clusters[clusters$group == "Ctrl",],
           aes(x =cell_type, y= Freq, fill = TCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 0) + 
  scale_fill_manual(values=color_TCR_clonetype_ctrl,
                    breaks = rev(order_TCR_clonetype))+
  labs(fill = "Ctrl")+
  labs(x=NULL,y = 'Number of Cells')+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1,size = rel(1)),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))+
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim = c(0, 19000))

ggsave("figS3/s3b_T&NK_clonetype_stackbar.pdf",p,width = 7, height = 4)
```

# s3c T8 pattern 1a vs 1b DEG volcano

```{r}
disease_pattern <- readRDS("rds/T8_disease_TCRpattern.rds")
DefaultAssay(disease_pattern) <- "RNA"
```

```{r}
DEG <- FindMarkers(disease_pattern,
                   group.by = "pattern",ident.1 = "pattern 1a", ident.2 = "pattern 1b",
                   test.use = "MAST")
write.csv(DEG, "sTable/s3c_DEG_T8_pattern_1a.vs.1b.csv")
```

```{r}
dput(rownames(subset(DEG,DEG$avg_log2FC > 1 | DEG$avg_log2FC < -1)))
```

```{r}
gene_selected <- c("IFI27", "GZMB",  "ISG15", "LGALS1",
"TYMS", "HMGN2", "STMN1", "MKI67", "GNLY", 
"RRM2", "TUBB", "HMGB2", "TUBA1B", "HIST1H4C")
```


```{r}
p = EnhancedVolcano(DEG,lab = rownames(DEG),
                    x = 'avg_log2FC',y = 'p_val_adj',
                    title = "T8 Pneumonia pattern 1a vs 1b",
                    subtitle = NULL,
                    cutoffLineType = "dotted",
                    col = c("grey30", "forestgreen", "#2166ac", "#b2182b"),
                    drawConnectors = TRUE,widthConnectors = 0.75,colAlpha = 0.8,
                    FCcutoff = 1 ,pCutoff = 0.05,
                    pointSize = 2,
                    selectLab = gene_selected,
                    axisLabSize = 18, titleLabSize = 18,captionLabSize = 18) + 
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size = 16, colour = "black"),
        plot.title = element_text(hjust = 0.5,face = "bold",size = rel(1.5)))+
  NoLegend() 
ggsave("figS3/s3c_T8_volcano_pattern_1a.vs.1b.pdf", p,width = 5, height = 5)
```

# s3d T8 pattern 1a vs 1b DEG GO
```{r}
filtered_DEG_up <- subset(DEG,DEG$avg_log2FC > 0.5)
DEG_ego_BP_up <- data.frame(enrichGO(gene = row.names(filtered_DEG_up),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_up,'sTable/s3d_GO_BP_T8_disease_pattern_1a.vs.1b_up.csv') 

filtered_DEG_down <- subset(DEG,DEG$avg_log2FC < -0.5)
DEG_ego_BP_down <- data.frame(enrichGO(gene = row.names(filtered_DEG_down),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_down,'sTable/s3d_GO_BP_T8_disease_pattern_1a.vs.1b_down.csv') 


DEG_ego_BP_up$change <- c("up") 
DEG_ego_BP_down$change <- c("down") 

DEG_ego_BP_up <- DEG_ego_BP_up[order(DEG_ego_BP_up$qvalue),]
DEG_ego_BP_up_top15 <- DEG_ego_BP_up[1 : 15,]
DEG_ego_BP_up_top15$Description <- factor(DEG_ego_BP_up_top15$Description,
                                          levels = rev(DEG_ego_BP_up_top15$Description))

DEG_ego_BP_down <- DEG_ego_BP_down[order(DEG_ego_BP_down$qvalue),]
DEG_ego_BP_down_top15 <- DEG_ego_BP_down[1 : 15,]
DEG_ego_BP_down_top15$Description <- factor(DEG_ego_BP_down_top15$Description,
                                            levels = rev(DEG_ego_BP_down_top15$Description))
```


```{r}
p1 <- ggplot(data = DEG_ego_BP_up_top15,
            aes(x = Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Reds",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_y_discrete(position = "right")+
  scale_x_continuous(expand = c(0,0))+ylab(NULL)+ggtitle("pattern 1a")+
  theme_bw() + theme_GO +  
  theme(plot.title =  element_text(hjust = 0.5,face = "bold",colour = "black"),
        legend.position = "top")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size  = unit(0.12,"in"))

p2 <- ggplot(data = DEG_ego_BP_down_top15,
            aes(x = -Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Blues",direction = 1,,breaks= c(3,3.5,4,4.5), labels = c(3,3.5,4,4.5)) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_x_continuous(expand = c(0,0),breaks = c(-15,-10, -5,0),label = c("15","10", "5","0"))+
  theme_bw() + theme_GO + theme(legend.position = "left")+xlab("Count")+ggtitle("pattern 1b")+
  theme(plot.title =  element_text(hjust = 0.5,face = "bold",colour = "black"),
        legend.position = "top")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size = unit(0.12,"in"))

p= p2+p1
ggsave("figS3/s3d_T8_disease_GOBP_pattern_1a.vs.1b.pdf",p,width = 11,height = 4)
```



# s3e T8 pattern 1 vs 2 DEG volcano

```{r}
DEG <- FindMarkers(disease_pattern,
                   group.by = "pattern",ident.1 = c("pattern 1a","pattern 1b"), ident.2 = "pattern 2",
                   test.use = "MAST")
write.csv(DEG, "sTable/s3e_DEG_T8_pattern_1.vs.2.csv")
```

```{r}
dput(rownames(subset(DEG,DEG$avg_log2FC > 1 | DEG$avg_log2FC < -1)))
```

```{r}
gene_selected <- c( "COTL1", "CX3CR1",
"KLF2", "KLRG1", 
 "CXCR6", "ZNF683", "KLRC1", "FCGR3A", 
"CEBPD", "ITGA1", "KLRF1", 
 "KLRB1", "TYROBP", "IFI27", 
"CD27", "XCL2")
```


```{r}
p = EnhancedVolcano(DEG,lab = rownames(DEG),
                    x = 'avg_log2FC',y = 'p_val_adj',
                    title = "T8 Pneumonia pattern 1 vs 2",
                    subtitle = NULL,
                    cutoffLineType = "dotted",
                    col = c("grey30", "forestgreen", "#2166ac", "#b2182b"),
                    drawConnectors = TRUE,widthConnectors = 0.75,colAlpha = 0.8,
                    FCcutoff = 1 ,pCutoff = 0.05,
                    pointSize = 2,
                    selectLab = gene_selected,
                    axisLabSize = 18, titleLabSize = 18,captionLabSize = 18) + 
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size = 16, colour = "black"),
        plot.title = element_text(hjust = 0.5,face = "bold",size = rel(1.5)))+
  NoLegend() 
ggsave("figS3/s3e_T8_volcano_pattern_1.vs.2.pdf", p,width = 5, height = 5)
```

# s3f T8 pattern 1 vs 2 DEG GO
```{r}
filtered_DEG_up <- subset(DEG,DEG$avg_log2FC > 0.5)
DEG_ego_BP_up <- data.frame(enrichGO(gene = row.names(filtered_DEG_up),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_up,'sTable/s3f_GO_BP_T8_disease_pattern_1.vs.2_up.csv') 

filtered_DEG_down <- subset(DEG,DEG$avg_log2FC < -0.5)
DEG_ego_BP_down <- data.frame(enrichGO(gene = row.names(filtered_DEG_down),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_down,'sTable/s3f_GO_BP_T8_disease_pattern_1.vs.2_down.csv') 


DEG_ego_BP_up$change <- c("up") 
DEG_ego_BP_down$change <- c("down") 

DEG_ego_BP_up <- DEG_ego_BP_up[order(DEG_ego_BP_up$qvalue),]
DEG_ego_BP_up_top15 <- DEG_ego_BP_up[1 : 15,]
DEG_ego_BP_up_top15$Description <- factor(DEG_ego_BP_up_top15$Description,
                                          levels = rev(DEG_ego_BP_up_top15$Description))

DEG_ego_BP_down <- DEG_ego_BP_down[order(DEG_ego_BP_down$qvalue),]
DEG_ego_BP_down_top15 <- DEG_ego_BP_down[1 : 15,]
DEG_ego_BP_down_top15$Description <- factor(DEG_ego_BP_down_top15$Description,
                                            levels = rev(DEG_ego_BP_down_top15$Description))
```

```{r}
p1 <- ggplot(data = DEG_ego_BP_up_top15,
            aes(x = Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Reds",direction = 1,breaks=c(6,7,8)) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_y_discrete(position = "right")+
  scale_x_continuous(expand = c(0,0))+ylab(NULL)+ggtitle("pattern 1")+
  theme_bw() + theme_GO +  
  theme(plot.title =  element_text(hjust = 0.5,face = "bold",colour = "black"),
        legend.position = "top")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size = unit(0.1,"in"))

p2 <- ggplot(data = DEG_ego_BP_down_top15,
            aes(x = -Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Blues",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_x_continuous(expand = c(0,0),breaks = c(-15,-10, -5,0),label = c("15","10", "5","0"))+
  theme_bw() +theme_GO+theme(legend.position = "left")+xlab("Count")+ggtitle("pattern 2")+
  theme(plot.title =  element_text(hjust = 0.5,face = "bold",colour = "black"),
        legend.position = "top")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size = unit(0.1,"in"))

p= p2+p1
ggsave("figS3/s3f_T8_disease_GOBP_pattern_1.vs.2.pdf",p,width = 12,height = 4)
```

# s3g T4 TCR clonetype DimPlot

```{r}
scRNAsubT4 <- readRDS("rds/scRNAsubT4_anno_TCRID_Cycling.NoCD8A.rds")
DefaultAssay(scRNAsubT4) <- "RNA"
```

```{r}
scRNAsubT4$cell_type_main<- factor(scRNAsubT4$cell_type_main, levels = order_T4)
scRNAsubT4$TCR_clonetype <- factor(scRNAsubT4$TCR_clonetype, levels =order_TCR_clonetype)
```

```{r}
scRNA <- scRNAsubT4[,scRNAsubT4$patient != "C2"]
md <- cbind(Embeddings(scRNA[["umap"]]),scRNA[["TCR_clonetype"]],scRNA[["disease"]])

p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Pneumonia",], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Pneumonia",],shape = 16,size = 1,alpha = 0.8)  +
  scale_color_manual(values = color_TCR_clonetype_disease)+
  labs(colour = "Pneumonia")+
  theme_cowplot()+
  theme_blank+NoLegend()

ggsave("figS3/s3g_DimPlot_T4_clonetype_disease.png",p, width = 5, height = 5)
```


```{r}
p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Ctrl",], color = "lightgrey", size = 1)  +
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"),
             shape = 16,size = 1,alpha = 0.8) +
  scale_color_manual(values = color_TCR_clonetype_ctrl)+
  labs(colour = "Ctrl")+
  theme_cowplot()+
  theme_blank+NoLegend()
ggsave("figS3/s3g_DimPlot_T4_clonetype_ctrl.png",p, width = 5, height = 5)
```

```{r}
p = ggplot(md[!is.na(md$TCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"))+
  geom_point(data = md[is.na(md$TCR_clonetype) & md$disease == "Pneumonia",], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Pneumonia",],shape = 16,size = 1,alpha = 0.8)  +
  scale_color_manual(values = color_TCR_clonetype_disease,
                     breaks = rev(order_TCR_clonetype))+
  labs(colour = "Pneumonia")+new_scale("color")+
  geom_point(data = md[!is.na(md$TCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "TCR_clonetype"),
             shape = 16,size = 1,alpha = 0.8) +
  scale_color_manual(values = color_TCR_clonetype_ctrl,
                     breaks = rev(order_TCR_clonetype))+
  labs(colour = "Ctrl")+
  theme_cowplot()+
  theme_blank
l=as_ggplot(get_legend(p)) 
ggsave('figS3/s3g_DimPlot_T4_clonetype_legend.pdf', l)
```

# s3h T4 clonetype expansion
```{r}
clusters <- data.frame(table(scRNA$TCR_clonetype, scRNA$disease,scRNA$cell_type_main))
colnames(clusters)[1:3]<- c("TCR_clonetype","group","cell_type")
clusters <- clusters[order(clusters$cell_type,clusters$group,clusters$TCR_clonetype),]

p = ggplot(clusters) + 
  geom_bar(data = clusters[clusters$group == "Pneumonia",],
           aes(x =cell_type, y= Freq, fill = TCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 1) + 
  scale_fill_manual(values=color_TCR_clonetype_disease,
                    breaks = rev(order_TCR_clonetype))+
  labs(fill = "Pneumonia")+new_scale("fill")+
  geom_bar(data = clusters[clusters$group == "Ctrl",],
           aes(x =cell_type, y= Freq, fill = TCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 0) + 
  scale_fill_manual(values=color_TCR_clonetype_ctrl,
                    breaks = rev(order_TCR_clonetype))+
  labs(fill = "Ctrl")+
  labs(x=NULL,y = 'Number of Cells')+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1,size = rel(1)),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))+
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim = c(0, 6300))

ggsave("figS3/s3h_T4_clonetype_stackbar.pdf",p,width = 7, height = 4)
```

# s3i T4 TCR transition index
## disease
```{r}
disease <- scRNAsubT4[,scRNAsubT4$disease == "Pneumonia"]

meta <- disease@meta.data
meta <- subset(meta,meta$TCR_clonetype != "Single (X = 1)")
meta$Cell_Name <- rownames(meta)
meta$clone.id <- meta$TCR_ID
meta$majorCluster <- meta$cell_type_main
meta$loc <- meta$sample_type
meta <- subset(meta, meta$clone.id != "NA")

tic("Startrac.run")
out <- Startrac.run(meta, proj="T4",verbose=F)
toc()

df = out@pIndex.tran
df <- subset(df, df$aid == "T4")
rownames(df) <- df$majorCluster
df$aid <- NULL
df$majorCluster <- NULL
df <- myfill(df)
p = Heatmap(df,name = "pIndex.tran", column_names_rot = 45,
        col=colorRampPalette(rev(brewer.pal(n = 7, name ="RdBu")))(100),
        heatmap_legend_param = list(labels_gp = gpar(font = 16),direction = "vertical"),
        width = unit(2, "in"), height = unit(2, "in"),
        column_names_gp = gpar(fontsize = 14),row_names_gp = gpar(fontsize = 14))
pdf("figS3/s3i_T4_transition_index_disease.pdf",width = 4,height = 3)
draw(p)
dev.off()
```

## ctrl
```{r}
ctrl <- scRNAsubT4[,scRNAsubT4$disease == "Ctrl" & scRNAsubT4$patient != "C2"]

meta <- ctrl@meta.data
meta <- subset(meta,meta$TCR_clonetype != "Single (X = 1)")
meta$Cell_Name <- rownames(meta)
meta$clone.id <- meta$TCR_ID
meta$majorCluster <- meta$cell_type_main
meta$loc <- meta$sample_type
meta <- subset(meta, meta$clone.id != "NA")

tic("Startrac.run")
out <- Startrac.run(meta, proj="T4",verbose=F)
toc()

df = out@pIndex.tran
df <- subset(df, df$aid == "T4")
rownames(df) <- df$majorCluster
df$aid <- NULL
df$majorCluster <- NULL
df <- myfill(df)
p = Heatmap(df,name = "pIndex.tran", column_names_rot = 45,
        col=colorRampPalette(rev(brewer.pal(n = 7, name ="RdBu")))(100),
        heatmap_legend_param = list(labels_gp = gpar(font = 16),direction = "vertical"),
        width = unit(2, "in"), height = unit(2, "in"),
        column_names_gp = gpar(fontsize = 14),row_names_gp = gpar(fontsize = 14))
pdf("figS3/s3i_T4_transition_index_ctrl.pdf",width = 4,height = 3)
draw(p)
dev.off()
```

# s3j T4 clonetype migration (group:disease) 
```{r}
disease <- scRNAsubT4[,scRNAsubT4$disease == "Pneumonia"]

metadata <- disease@meta.data
da.tcr.st1 <- metadata %>% 
  ungroup() %>% 
  mutate(Cell_Name=rownames(metadata), 
         clone.id = metadata$TCR_ID, 
         majorCluster=metadata$cell_type_main, 
         loc=metadata$sample_type) %>%
  dplyr::select(Cell_Name,clone.id,patient,majorCluster,loc,group,patient) %>% 
  as.data.frame()
da.tcr.st2 <- na.omit(da.tcr.st1)
```

```{r}
obj <- new("Startrac",da.tcr.st2,aid="T4cell")
obj <- calIndex(obj)
clus.data = obj@cluster.data

tic("pIndex")
obj <- pIndex(obj)
toc()

df.migr <- obj@pIndex.migr
df.migr <- df.migr[,-1]
rownames(df.migr)=df.migr[,1]
df.migr=df.migr[,-1]
df.migr <- as.data.frame(df.migr)

df.migr.2 <-gather(df.migr, migr, value, 1:3)
df.migr.2$majorCluster <- rep(rownames(df.migr),3)


df.migr.2$majorCluster<- factor(df.migr.2$majorCluster, levels =order_T4)
df.migr.2 <- subset(df.migr.2, !(df.migr.2$majorCluster %in% c("T4_Tm","T4_Tn") ))
# no break
p=ggplot(df.migr.2, aes(x=majorCluster, y=value, fill=migr)) +
  geom_bar(stat="identity", position=position_dodge(),width=.8)+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim = c(0, 0.35))+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust =1, vjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 14))+
  scale_fill_manual(values=color_migr)+
  xlab(NULL)+ylab("T4 TCR migration index")

ggsave("figS3/s3j_T4_migration_celltype.pdf",p,width = 8, height = 4)
```

