---
title: "FigureS5"
author: "YueanZhao"
output: html_document
---
```{r}
rm(list = ls())
gc()
```

```{r}
scRNAsubB <- readRDS("rds/scRNAsubB_anno_BCR.rds")
DefaultAssay(scRNAsubB) <- "RNA"
```

```{r}
scRNAsubB$cell_type_B <- factor(scRNAsubB$cell_type_B, levels = order_B)
scRNAsubB$cell_type_main <- factor(scRNAsubB$cell_type_main, levels = order_B_main)
scRNAsubB$isotype <- factor(scRNAsubB$isotype, levels = order_isotype)
scRNAsubB$BCR_clonetype <- factor(scRNAsubB$BCR_clonetype, levels = order_BCR_clonetype)
scRNAsubB$disease <- factor(scRNAsubB$disease, levels = order_disease)
```

# s5a B&plasma featureplot

```{r}
scRNAsubB <- SetIdent(scRNAsubB,value = "cell_type_B")
DefaultAssay(scRNAsubB) <- "RNA"
B.all.markers <- FindAllMarkers(scRNAsubB, 
                              only.pos = TRUE, test.use = "MAST",
                              min.pct = 0.25, logfc.threshold = 0.5)
B.top10 = B.all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
write.csv(B.all.markers, "sTable/s5a_all_markers_B_MAST.csv", row.names = F)
write.csv(B.top10, "sTable/s5a_top10_markers_B_MAST.csv", row.names = F)
```

```{r}
#plot featureplots
DefaultAssay(scRNAsubB) <- "RNA"
B_genelist = c("MS4A1",#B
               "CD9",#B_MZ
               "CD83", #B_GC
               "IGHD","IGHM","SELL", #B_naive
               "BACH2",#B_pre_mem
               "CD19", #Bmem
               "MKI67","CD27",
               "XBP1","MZB1","JCHAIN","IGHG1","IGHA1","CD38")

beach = c( "4"="#87D2DB","1"="#5BB1CB","6"="#4F66AF","3"="#F15F30","5"="#F7962E","2"="#FCEE2B")

plot.list <- lapply(X = B_genelist, FUN = function(x) {
    FeaturePlot(scRNAsubB ,cols = beach, features = x, raster = F,order = T)+
    NoLegend()+
    theme(axis.title=element_blank(),axis.text=element_blank(),
          axis.ticks=element_blank(),axis.line=element_blank(),
          plot.title = element_blank())
})

p <- wrap_plots(plots = plot.list, nrow=2)    
ggsave("figS5/s5a_B_featureplot.png", plot = p, width = 32 , height = 8) 

#plot the legend
p = FeaturePlot(scRNAsubB,cols = beach, features = "XBP1", raster = F)
l=as_ggplot(get_legend(p)) 
ggsave('figS5/s5a_B_featureplot_Legend.pdf', l)
```

# s5b PC PB heatmap
```{r}
plasma <- scRNAsubB[,scRNAsubB$cell_type_B %in% c("PC.1","PC.2","PC.3","PB")]
plasma <- plasma[,plasma$disease == "Pneumonia"]
plasma$cell_type_B <- factor(plasma$cell_type_B,levels = c("PC.3","PC.2","PC.1","PB"))
```

```{r}
DefaultAssay(plasma) <- "RNA"
plasma_genes <- c("IGHA1","IGHA2","IGHG1","IGHG2","IGHG3","IGHG4",
                  "CXCR6","CXCR3","CXCL10","CXCL16","CCR1","CCR2","CCR5",
                  "CCL1","CCL2","CCL3","CCL4","CCL5","CCL3L1",
                  "HLA-A","HLA-B","HLA-C","HLA-E","HLA-F",
                  "HLA-DRA","HLA-DRB1","HLA-DRB5","HLA-DQA1","HLA-DQB1","HLA-DPB1","HLA-DMA","HLA-DMB1")

plasma <- SetIdent(plasma,value = "cell_type_B")

plasma_genes <- intersect(plasma_genes, rownames(GetAssayData(plasma, slot = 'data')))
mat <- AverageExpression(plasma, features = plasma_genes, slot = 'data',assays = "RNA")
mat1 <- scale(t(mat$RNA))


p = Heatmap(mat1, name = "avg_Exp", cluster_rows = F, cluster_columns = F,
            row_names_side = "left", row_dend_side = "right",row_order = c("PB","PC.1","PC.2","PC.3"),
            col = colorRamp2(c(-2, 0, 2), c("#4D9221","#F7F7F7","#C51B7D")),
            column_names_rot = 45,
            column_names_gp = gpar(fontsize = 14),
            row_names_gp = gpar(fontsize = 16),
            heatmap_legend_param = list(labels_gp = gpar(fontsize = 14),
                                                     direction = "vertical",
                                                     title_gp = gpar(fontsize = 14,face = "bold")))

pdf("figS5/s5b_plasma_heatmap.pdf",width = 9,height = 4)
draw(p)
dev.off()
```

# s5c PC&PB_GO_DvsC
```{r}
plasma <- scRNAsubB[,scRNAsubB$cell_type_B %in% c("PC.1","PC.2","PC.3","PB")]
plasma <- plasma[,!(plasma$patient %in% "C2")]
DEG <- FindMarkers(plasma,group.by = "disease",ident.1 = "Pneumonia", ident.2 = "Ctrl",test.use = "MAST")
write.csv(DEG, "sTable/s5c_DEG_PC&PB_Disease.vs.Ctrl.csv")
```

```{r}
filtered_DEG_up <- subset(DEG,DEG$avg_log2FC > 1)
DEG_ego_BP_up <- data.frame(enrichGO(gene = row.names(filtered_DEG_up),
                                  OrgDb         = 'org.Hs.eg.db',
                                  keyType       = 'SYMBOL',
                                  ont           = "BP",
                                  pAdjustMethod = "BH",
                                  pvalueCutoff  = 0.01,
                                  qvalueCutoff  = 0.05) )
write.csv(DEG_ego_BP_up,'sTable/s5c_GO_BP_up_PC&PB_Disease.vs.Ctrl.csv') 

DEG_ego_BP_up$change <- c("up") 
DEG_ego_BP_up <- DEG_ego_BP_up[order(DEG_ego_BP_up$qvalue),]
DEG_ego_BP_up_top15 <- DEG_ego_BP_up[1 : 15,]
DEG_ego_BP_up_top15$Description <- factor(DEG_ego_BP_up_top15$Description,
                                          levels = rev(DEG_ego_BP_up_top15$Description))

```


```{r}
p <- ggplot(data = DEG_ego_BP_up_top15,
            aes(x = Count,y = Description, fill = -log10(qvalue)))+
  scale_fill_distiller(palette = "Reds",direction = 1) +
  geom_bar(stat = "identity",width = 0.8) +
  scale_y_discrete(position = "left")+
  scale_x_continuous(expand = c(0,0))+ylab(NULL)+
  ggtitle("Pneumonia Plasma cells & Plasmablast Upregulated Pathways")+
  theme_bw() +theme_GO+  
  theme(plot.title =  element_text(hjust = 0.5,size = rel(1),face = "bold",colour = "black"),
        legend.position = "right")+
  theme(legend.title = element_text(size = 10),legend.text = element_text(size = 10),
        legend.key.size = unit(0.2,"in"))

ggsave("figS5/s5c_PC&PB_GO_DvsC.pdf",p,width = 8,height = 4)
```

# s5d: DimPlot by BCR clonetype
```{r}
scRNA <- scRNAsubB[,scRNAsubB$patient != "C2"]
md <- cbind(Embeddings(scRNA[["umap"]]),scRNA[["BCR_clonetype"]],scRNA[["disease"]])

p = ggplot(md[!is.na(md$BCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "BCR_clonetype"))+
  geom_point(data = md[is.na(md$BCR_clonetype),], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$BCR_clonetype) & md$disease == "Pneumonia",],
             shape = 16,size = 2,alpha = 0.8)  +
  scale_color_manual(values = color_BCR_clonetype_disease)+
  labs(colour = "Pneumonia")+ new_scale("color") + 
  geom_point(data = md[!is.na(md$BCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "BCR_clonetype"),
             shape = 16,size = 2,alpha = 0.8) +
  scale_color_manual(values = color_BCR_clonetype_ctrl)+
  labs(colour = "Ctrl")+
  theme_cowplot()+
  theme_blank+NoLegend()

ggsave("figS5/s5d_DimPlot_B_clonetype_merge.png",p, width = 5, height = 5)
```

```{r}
p = ggplot(md[!is.na(md$BCR_clonetype),], 
           aes_string(x = "UMAP_1", y = "UMAP_2", color = "BCR_clonetype"))+
  geom_point(data = md[is.na(md$BCR_clonetype),], color = "lightgrey", size = 1)  + 
  geom_point(data = md[!is.na(md$BCR_clonetype) & md$disease == "Pneumonia",],
             shape = 16,size = 2,alpha = 0.8)  +
  scale_color_manual(values = color_BCR_clonetype_disease,
                     breaks = rev(order_BCR_clonetype))+
  labs(colour = "Pneumonia")+ new_scale("color") + 
  geom_point(data = md[!is.na(md$BCR_clonetype) & md$disease == "Ctrl",],
             aes_string(x = "UMAP_1", y = "UMAP_2", color = "BCR_clonetype"),
             shape = 16,size = 2,alpha = 0.8) +
  scale_color_manual(values = color_BCR_clonetype_ctrl,
                     breaks = rev(order_BCR_clonetype))+
  labs(colour = "Ctrl")+
  theme_cowplot()+
  theme_blank

l=as_ggplot(get_legend(p)) 
ggsave('figS5/s5d_DimPlot_B_clonetype_merge_legend.pdf', l)
```

# s5e: BCR clonetype stacked bar
```{r}
clusters <- data.frame(table(scRNA$BCR_clonetype, scRNA$disease,scRNA$cell_type_B))
colnames(clusters)[1:3]<- c("BCR_clonetype","group","cell_type")
clusters <- clusters[order(clusters$cell_type,clusters$group,clusters$BCR_clonetype),]
clusters <- subset(clusters, !(clusters$BCR_clonetype %in% "Single (n = 1)"))

p = ggplot(clusters) + 
  geom_bar(data = clusters[clusters$group == "Pneumonia",],
           aes(x =cell_type, y= Freq, fill = BCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 1) + 
  scale_fill_manual(values=color_BCR_clonetype_disease,
                    breaks = rev(order_BCR_clonetype))+
  labs(fill = "Pneumonia")+new_scale("fill")+
  geom_bar(data = clusters[clusters$group == "Ctrl",],
           aes(x =cell_type, y= Freq, fill = BCR_clonetype, group = group),
           position ="stack",stat = "identity",width = 0.4,just = 0) + 
  scale_fill_manual(values=color_BCR_clonetype_ctrl,
                    breaks = rev(order_BCR_clonetype))+
  labs(fill = "Ctrl")+
  labs(x=NULL,y = 'Number of Cells')+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1,size = rel(1)),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 14))+
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim = c(0, 970))

ggsave("figS5/s5e_BCR_clonetype_stackbar.pdf",p,width = 7, height = 4)
```

# s5f BCR transition index
```{r}
disease <- scRNAsubB[,scRNAsubB$disease == "Pneumonia"]

meta <- disease@meta.data
meta <- subset(meta,meta$BCR_clonetype != "Single (X = 1)")
meta$Cell_Name <- rownames(meta)
meta$clone.id <- meta$BCR_ID
meta$majorCluster <- meta$cell_type
meta$loc <- meta$sample_type
meta <- subset(meta, meta$clone.id != "NA")

tic("Startrac.run")
out <- Startrac.run(meta, proj="B",verbose=F)
toc()

pdf("figS5/s5f_B_transition_index_disease.pdf",width=3.8,height=3)
Startrac::plot(out,index.type="pairwise.tran",byPatient=T)
dev.off()

df = out@pIndex.tran
df <- subset(df, df$aid == "B")
rownames(df) <- df$majorCluster
df$aid <- NULL
df$majorCluster <- NULL
df <- myfill(df)
p = Heatmap(df,name = "pIndex.tran", column_names_rot = 45,
        col=colorRampPalette(rev(brewer.pal(n = 7, name ="RdBu")))(100),
        heatmap_legend_param = list(labels_gp = gpar(font = 16),direction = "vertical"),
        width = unit(2.5, "in"), height = unit(2.5, "in"),
        column_names_gp = gpar(fontsize = 14),row_names_gp = gpar(fontsize = 14))

pdf("figS5/s5f_B_transition_index_disease.pdf",width=5,height=4)
draw(p)
dev.off()
```




